name: 'coverage'
on:
    pull_request:
        branches:
            - release/*
            - main
jobs:
    coverage:
        permissions:
            pull-requests: write
            contents: read
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Python 3.10
            uses: actions/setup-python@v3
            with:
              python-version: '3.10'
          - name: Install requirements
            run: >-
                python -m pip install -r binder_trace/requirements.txt
          - name: Run coverage
            run: >-
                python -m pytest --cov binder_trace --cov-report xml:bt-coverage.xml
          - name: Get Cover 
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: bt-coverage.xml
                thresholdNew: 0.8
                thresholdModified: 0.8
                token: ${{ secrets.GITHUB_TOKEN }}
